config/routes.rb
Rails.application.routes.draw do
  root 'login#index'

  resources :document

  resources :interest_profile

  get 'login' => 'login#index'

  post 'login' => 'login#create'
  
  get 'logout' => 'login#logout'

  get 'search/results' => 'search#results'
  resources :search

  

end

app/models/search.rb
class Search
  def self.text_search(profile, query, page = 1, skip_query_creation = false)
    Query.create(:interest_profile => profile, :query => query) unless skip_query_creation

    return Document.search("text:#{query}").page(page).per_page(10).results
  end

  def self.cairn_search(profile, query, page = 1, skip_query_creation = false, predicted_weight = 0.7)
    Query.create(:interest_profile => profile, :query => query) unless skip_query_creation

    docs = Document.search("text:#{query}").page(page).per_page(10).results

    predicted_scores = {}

    docs.each do |document|
      ratings = DocumentRating.where('interest_profile_id != ? AND document_id = ?', profile.id, document.id)
      score = 0
      sim_score_sum = 0
      ratings.each do |rating|
        sim_score = profile.similarity_score(rating.interest_profile)
        score += rating.rating*sim_score
        sim_score_sum += sim_score
      end
      predicted_scores[document.id] = 0
      predicted_scores[document.id] = score / sim_score_sum unless sim_score_sum == 0
    end

    docs.sort_by{|x| x._score*( 1 - predicted_weight ) + predicted_scores[x.id]*( predicted_weight )}.reverse
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter :ensure_login

  def index
  end

  def cairn
  end

  def text
  end

  def results
    redirect_to :search and return if params[:query].blank?
    skip_query_creation = !params[:page].nil?
    if params[:type] == 'cairn'
      @results = Search.cairn_search(@profile, params[:query], params[:page], skip_query_creation)
    else
      @results = Search.text_search(@profile, params[:query], params[:page], skip_query_creation)
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/cairn.html.erb
<h1>Search#cairn</h1>
<p>Find me in app/views/search/cairn.html.erb</p>

app/views/search/index.html.erb
<!-- Main text area for search results and sidebars -->
<div id="content">

</div>

app/views/search/results.html.erb
<!-- Main text area for search results and sidebars -->
<div id="content">

  <!-- Main search results -->
  <div id="main">
    <% if @results.size == 0 %>
      No results for "<%= params[:query]%>"
    <% end %>

    <% @results.each do |doc| %>
      <div class="result-item">
        <%= link_to doc.docno, document_path(doc.id), :class => 'document-link' %>
        <div class="document-text"><%= truncate(doc.text, length: 150, separator: ' ') %></div>
      </div>
    <% end %>

    <%= will_paginate @results %>
  </div>

  <!-- Similar Users sidebar -->
  <div id="SimUsers">
    <form action="" method="get" name="Similar Users"></form>
  </div>

  <!-- Recommended Queries sidebar -->
  <div id="RecQs">
    <form action="" method="get" name="Recommended Queries"></form>
  </div>

  <!-- Common Regions sidebar -->
  <div id="ComRegs">
    <form action="" method="get" name="Common Regions"></form>
  </div>


</div>

app/views/search/text.html.erb
<!-- Main text area for search results and sidebars -->
<div id="content">

  <!-- Main search results -->
  <div id="main">
    <form action="" method="post" name="Search Results"></form>
  </div>

  <!-- Similar Users sidebar -->
  <div id="SimUsers">
    <form action="" method="get" name="Similar Users"></form>
  </div>

  <!-- Recommended Queries sidebar -->
  <div id="RecQs">
    <form action="" method="get" name="Recommended Queries"></form>
  </div>

  <!-- Common Regions sidebar -->
  <div id="ComRegs">
    <form action="" method="get" name="Common Regions"></form>
  </div>


</div>